name: build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      working-directory: web-app
      run: npm install

    - name: Run Unit Tests
      working-directory: web-app
      run: npm test      
   
    - name: Build the Docker image and push to AWS ECR
      working-directory: web-app
      run: |
        docker build -t besant .
      